"""10-K / 10-Q section extraction. SPEC §9.

A 10-K runs to hundreds of pages against an 8k usable context, so the document
cannot be handed to the model whole. Target sections are extracted first by
deterministic HTML heading parsing, then chunked, then summarized
hierarchically.

SPEC §9 calls this "its own tested component with a known failure rate", which
is the right framing: EDGAR HTML is generated by dozens of filing agents with
no shared structure, and heading detection will fail on some of them. The
honest response is to measure the rate and report it, which is what
`ExtractionOutcome` and Phase 9 criterion 4 are for.

**A failed extraction returns nothing rather than the wrong section.**
Summarizing Item 7A while labelling it Item 7 would produce a confident
summary of the wrong thing, which is worse than no summary.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from enum import StrEnum

_TAGS = re.compile(r"<[^>]+>")
_WHITESPACE = re.compile(r"[ \t\xa0]+")
_BLANK_LINES = re.compile(r"\n{3,}")


class Section(StrEnum):
    """The sections SPEC §9 names as extraction targets."""

    RISK_FACTORS = "item_1a_risk_factors"
    MDNA = "item_7_mdna"
    MARKET_RISK = "item_7a_market_risk"
    BUSINESS = "item_1_business"
    LEGAL = "item_3_legal"


#: Heading patterns per section. Item numbers are the anchor because they are
#: the one thing filers agree on; the title text varies ("Risk Factors",
#: "RISK FACTORS", "Item 1A. Risk Factors").
SECTION_PATTERNS: dict[Section, re.Pattern[str]] = {
    Section.BUSINESS: re.compile(r"item\s*1\s*[.\-–—:]?\s*business", re.IGNORECASE),
    Section.RISK_FACTORS: re.compile(r"item\s*1a\s*[.\-–—:]?\s*risk\s*factors", re.IGNORECASE),
    Section.LEGAL: re.compile(r"item\s*3\s*[.\-–—:]?\s*legal\s*proceedings", re.IGNORECASE),
    Section.MDNA: re.compile(
        r"item\s*7\s*[.\-–—:]?\s*management.{0,5}s\s*discussion", re.IGNORECASE
    ),
    Section.MARKET_RISK: re.compile(
        r"item\s*7a\s*[.\-–—:]?\s*quantitative\s*and\s*qualitative", re.IGNORECASE
    ),
}

#: Where each section ends: the heading of whatever follows it.
SECTION_ENDS: dict[Section, tuple[Section | re.Pattern[str], ...]] = {
    Section.BUSINESS: (Section.RISK_FACTORS,),
    Section.RISK_FACTORS: (
        re.compile(r"item\s*1b\s*[.\-–—:]?\s*unresolved", re.IGNORECASE),
        re.compile(r"item\s*2\s*[.\-–—:]?\s*propert", re.IGNORECASE),
    ),
    Section.LEGAL: (re.compile(r"item\s*4\s*[.\-–—:]?\s*mine\s*safety", re.IGNORECASE),),
    Section.MDNA: (Section.MARKET_RISK,),
    Section.MARKET_RISK: (
        re.compile(r"item\s*8\s*[.\-–—:]?\s*financial\s*statements", re.IGNORECASE),
    ),
}

#: A "section" shorter than this is a table-of-contents entry, not the section
#: itself. Filings list every item twice -- once in the TOC, once for real --
#: and taking the first match gives a one-line summary of a heading.
MIN_SECTION_CHARS = 500

#: Dot leaders, or a heading trailed by a bare page number. Both mark a
#: table-of-contents line.
#:
#: Length alone does not catch these. A TOC entry for a section that has no
#: body -- an incorporated-by-reference item, say -- has no following heading
#: to stop at, so it runs to the end of the document and arrives looking like
#: a long, healthy section. That is the "confident summary of the wrong thing"
#: this module exists to prevent, so the start match is rejected outright.
_TOC_LINE = re.compile(r"\.{4,}|\.\s\.\s\.|\s\d{1,3}\s*$")


class ExtractionOutcome(StrEnum):
    EXTRACTED = "extracted"
    HEADING_NOT_FOUND = "heading_not_found"
    TOO_SHORT = "too_short"
    NO_END_BOUNDARY = "no_end_boundary"


@dataclass(frozen=True, slots=True)
class ExtractedSection:
    section: Section
    outcome: ExtractionOutcome
    text: str = ""
    char_count: int = 0

    @property
    def succeeded(self) -> bool:
        return self.outcome is ExtractionOutcome.EXTRACTED


def strip_html(html: str) -> str:
    """HTML to plain text, preserving paragraph breaks.

    Not a full parser: filings use nested tables for layout, and a real parser
    would reconstruct the layout rather than the prose. Line structure is what
    heading detection needs.
    """
    text = re.sub(r"<(br|/p|/div|/tr)[^>]*>", "\n", html, flags=re.IGNORECASE)
    text = _TAGS.sub(" ", text)
    text = (
        text.replace("&nbsp;", " ")
        .replace("&amp;", "&")
        .replace("&#8217;", "'")
        .replace("&#146;", "'")
        .replace("&rsquo;", "'")
    )
    text = _WHITESPACE.sub(" ", text)
    return _BLANK_LINES.sub("\n\n", text).strip()


def _is_contents_line(text: str, position: int) -> bool:
    """Is the heading at ``position`` a table-of-contents entry?"""
    line_start = text.rfind("\n", 0, position) + 1
    line_end = text.find("\n", position)
    line = text[line_start : line_end if line_end != -1 else len(text)]
    return bool(_TOC_LINE.search(line))


def extract_section(html_or_text: str, section: Section) -> ExtractedSection:
    """Pull one section out of a filing.

    Takes the LAST heading match rather than the first, because the first is
    almost always the table of contents. Where that heuristic fails the result
    is short and is reported as TOO_SHORT rather than returned as a section.
    """
    text = strip_html(html_or_text) if "<" in html_or_text[:2000] else html_or_text

    starts = [
        match
        for match in SECTION_PATTERNS[section].finditer(text)
        if not _is_contents_line(text, match.start())
    ]
    if not starts:
        return ExtractedSection(section, ExtractionOutcome.HEADING_NOT_FOUND)

    start = starts[-1].start()

    end = len(text)
    found_boundary = False
    for boundary in SECTION_ENDS.get(section, ()):
        pattern = SECTION_PATTERNS[boundary] if isinstance(boundary, Section) else boundary
        match = pattern.search(text, start + 50)
        if match:
            end = min(end, match.start())
            found_boundary = True

    body = text[start:end].strip()
    if len(body) < MIN_SECTION_CHARS:
        # Almost certainly a table-of-contents line. Returning it would give
        # the model a heading and let it summarize from its own knowledge.
        return ExtractedSection(section, ExtractionOutcome.TOO_SHORT, char_count=len(body))

    if not found_boundary:
        # Ran to the end of the document. Usable, but flagged: it may have
        # swallowed later sections.
        return ExtractedSection(
            section, ExtractionOutcome.NO_END_BOUNDARY, text=body, char_count=len(body)
        )

    return ExtractedSection(section, ExtractionOutcome.EXTRACTED, text=body, char_count=len(body))


def chunk(text: str, *, max_chars: int = 6000, overlap: int = 200) -> list[str]:
    """Split for an 8k context, breaking on paragraphs where possible.

    The overlap exists so a sentence spanning a boundary is not lost to both
    chunks. Splitting mid-sentence is acceptable; losing the sentence is not.
    """
    if len(text) <= max_chars:
        return [text] if text else []

    chunks: list[str] = []
    position = 0
    while position < len(text):
        window = text[position : position + max_chars]
        if position + max_chars < len(text):
            split = window.rfind("\n\n")
            if split < max_chars // 2:
                split = window.rfind(". ")
            if split > max_chars // 2:
                window = window[: split + 1]
        chunks.append(window.strip())
        position += max(len(window) - overlap, 1)
    return [c for c in chunks if c]


@dataclass(frozen=True, slots=True)
class ExtractionReport:
    """Phase 9 criterion 4: the rate is documented, not assumed."""

    attempted: int
    succeeded: int
    outcomes: dict[str, int]

    @property
    def success_rate(self) -> float:
        return round(100.0 * self.succeeded / self.attempted, 1) if self.attempted else 0.0

    def render(self) -> str:
        lines = [
            f"Section extraction: {self.succeeded}/{self.attempted} ({self.success_rate:.1f}%)"
        ]
        lines.extend(f"  {k}: {v}" for k, v in sorted(self.outcomes.items()))
        return "\n".join(lines)


def build_report(results: list[ExtractedSection]) -> ExtractionReport:
    outcomes: dict[str, int] = {}
    for result in results:
        outcomes[result.outcome.value] = outcomes.get(result.outcome.value, 0) + 1
    return ExtractionReport(
        attempted=len(results),
        succeeded=sum(1 for r in results if r.succeeded),
        outcomes=outcomes,
    )
