"""intraday observations with mandatory delay

Revision ID: 691de1284751
Revises: a66f1a46d05a
Create Date: 2026-08-18 19:41:31.100320

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '691de1284751'
down_revision: str | None = 'a66f1a46d05a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intraday_observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('open', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('delay_seconds', sa.Integer(), nullable=False),
    sa.Column('is_delayed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('value_type', sa.String(length=24), server_default='observed', nullable=False),
    sa.Column('data_quality_flag', sa.String(length=32), server_default='ok', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_quality_flag IN ('ok', 'unverified_bootstrap', 'missing', 'quarantined', 'stale', 'conflicted', 'suspect_unit', 'premium_dependent')", name='ck_intraday_dq_flag'),
    sa.CheckConstraint("value_type IN ('observed', 'calculated', 'estimated', 'ai_interpreted')", name='ck_intraday_value_type'),
    sa.CheckConstraint('(delay_seconds = 0 AND is_delayed = false) OR (delay_seconds > 0 AND is_delayed = true)', name='ck_intraday_delay_agrees'),
    sa.CheckConstraint('(open IS NULL OR open >= 0) AND (high IS NULL OR high >= 0) AND (low IS NULL OR low >= 0) AND (close IS NULL OR close >= 0)', name='ck_intraday_non_negative'),
    sa.CheckConstraint('delay_seconds >= 0', name='ck_intraday_delay_non_negative'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'observed_at', 'interval_seconds', 'source', name='uq_intraday_sec_time_source')
    )
    op.create_index('ix_intraday_sec_time', 'intraday_observations', ['security_id', 'observed_at'], unique=False)
    # ### end Alembic commands ###


    # The append-only guard must cover this table from the moment it exists,
    # not from whenever someone remembers to add it.
    op.execute(
        """
        CREATE TRIGGER trg_intraday_observations_append_only
        BEFORE UPDATE OR DELETE ON intraday_observations
        FOR EACH ROW EXECUTE FUNCTION invest_reject_mutation();
        """
    )


def downgrade() -> None:
    op.execute(
        "DROP TRIGGER IF EXISTS trg_intraday_observations_append_only "
        "ON intraday_observations;"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_intraday_sec_time', table_name='intraday_observations')
    op.drop_table('intraday_observations')
    # ### end Alembic commands ###
