"""initial schema

Revision ID: b7ef09a83aff
Revises: 
Create Date: 2026-08-22 14:26:55.555547
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql
revision: str = 'b7ef09a83aff'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('benchmark_prices_daily',
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_document_url', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('data_quality', sa.Enum('current', 'delayed', 'stale', 'unavailable', 'estimated', 'manually_imported', name='data_quality'), nullable=False),
    sa.PrimaryKeyConstraint('symbol', 'trade_date')
    )
    op.create_index(op.f('ix_benchmark_prices_daily_source_id'), 'benchmark_prices_daily', ['source_id'], unique=False)
    op.create_table('companies',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sic', sa.String(length=4), nullable=True),
    sa.Column('sector_code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('active', 'delisted', 'acquired', 'merged', name='company_status'), nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=False),
    sa.Column('last_seen', sa.Date(), nullable=False),
    sa.Column('delisted_date', sa.Date(), nullable=True),
    sa.Column('inclusion_reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('cik')
    )
    op.create_index('ix_companies_sector', 'companies', ['sector_code'], unique=False)
    op.create_table('data_sources',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('staleness_threshold_hours', sa.Integer(), nullable=False),
    sa.Column('automation', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_review_queue',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_key', sa.String(length=512), nullable=False),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('best_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_cik', sa.String(length=10), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_key', name='uq_review_queue_identity')
    )
    op.create_table('macro_observations',
    sa.Column('series_id', sa.String(length=64), nullable=False),
    sa.Column('reference_period', sa.Date(), nullable=False),
    sa.Column('release_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_document_url', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('data_quality', sa.Enum('current', 'delayed', 'stale', 'unavailable', 'estimated', 'manually_imported', name='data_quality'), nullable=False),
    sa.PrimaryKeyConstraint('series_id', 'reference_period', 'release_timestamp')
    )
    op.create_index(op.f('ix_macro_observations_source_id'), 'macro_observations', ['source_id'], unique=False)
    op.create_table('raw_documents',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.LargeBinary(), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_record_id', 'content_hash', name='uq_raw_documents_identity')
    )
    op.create_index('ix_raw_documents_source', 'raw_documents', ['source_id', 'retrieved_at'], unique=False)
    op.create_table('watchlists',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('congressional_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filer_name', sa.Text(), nullable=False),
    sa.Column('filer_id', sa.String(length=64), nullable=False),
    sa.Column('chamber', sa.String(length=8), nullable=False),
    sa.Column('owner_type', sa.Enum('self', 'spouse', 'dependent', 'joint', 'unknown', name='owner_type'), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('asset_description', sa.Text(), nullable=False),
    sa.Column('transaction_type', sa.String(length=16), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('disclosure_date', sa.Date(), nullable=False),
    sa.Column('disclosure_lag_days', sa.Integer(), nullable=False),
    sa.Column('value_low_minor', sa.BigInteger(), nullable=False),
    sa.Column('value_high_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('parse_outcome', sa.Enum('text_extracted', 'ocr', 'review_queued', 'failed', 'manual_import', name='parse_outcome'), nullable=False),
    sa.Column('entity_match_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_document_url', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('data_quality', sa.Enum('current', 'delayed', 'stale', 'unavailable', 'estimated', 'manually_imported', name='data_quality'), nullable=False),
    sa.CheckConstraint('disclosure_date >= transaction_date', name='ck_congress_date_order'),
    sa.CheckConstraint('disclosure_lag_days >= 0', name='ck_congress_lag_nonneg'),
    sa.CheckConstraint('value_high_minor >= value_low_minor', name='ck_congress_bracket_order'),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filer_id', 'transaction_date', 'asset_description', 'transaction_type', 'value_low_minor', name='uq_congress_identity')
    )
    op.create_index('ix_congress_cik_date', 'congressional_transactions', ['cik', 'transaction_date'], unique=False)
    op.create_index('ix_congress_disclosure', 'congressional_transactions', ['disclosure_date'], unique=False)
    op.create_index(op.f('ix_congressional_transactions_source_id'), 'congressional_transactions', ['source_id'], unique=False)
    op.create_table('contradiction_items',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('check_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('fired', 'clear', 'unavailable', name='contradiction_status'), nullable=False),
    sa.Column('severity', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('cik', 'as_of', 'check_id')
    )
    op.create_table('entity_matches',
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('source_key', sa.String(length=512), nullable=False),
    sa.Column('resolved_cik', sa.String(length=10), nullable=True),
    sa.Column('method', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reviewed', sa.Boolean(), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_entity_confidence_range'),
    sa.ForeignKeyConstraint(['resolved_cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('source', 'source_key')
    )
    op.create_index('ix_entity_matches_below_gate', 'entity_matches', ['source'], unique=False, postgresql_where=sa.text('confidence < 0.85'))
    op.create_table('filings',
    sa.Column('accession', sa.String(length=25), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('acceptance_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('public_available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('primary_doc_url', sa.Text(), nullable=False),
    sa.Column('items', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('accession')
    )
    op.create_index('ix_filings_available', 'filings', ['public_available_at'], unique=False)
    op.create_index('ix_filings_cik_form', 'filings', ['cik', 'form_type', 'filed_date'], unique=False)
    op.create_table('government_contracts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('recipient_uei', sa.String(length=16), nullable=True),
    sa.Column('recipient_name', sa.Text(), nullable=False),
    sa.Column('award_id', sa.String(length=128), nullable=False),
    sa.Column('award_amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('agency', sa.Text(), nullable=True),
    sa.Column('naics', sa.String(length=8), nullable=True),
    sa.Column('entity_match_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_document_url', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('data_quality', sa.Enum('current', 'delayed', 'stale', 'unavailable', 'estimated', 'manually_imported', name='data_quality'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('award_id', 'action_date', 'award_amount_minor', name='uq_contract_identity')
    )
    op.create_index('ix_contract_cik_date', 'government_contracts', ['cik', 'action_date'], unique=False)
    op.create_index(op.f('ix_government_contracts_source_id'), 'government_contracts', ['source_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('job', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('running', 'success', 'partial', 'failed', name='ingestion_status'), nullable=False),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestion_runs_source_time', 'ingestion_runs', ['source_id', 'started_at'], unique=False)
    op.create_table('llm_outputs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('fact_set_hash', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_llm_outputs_lookup', 'llm_outputs', ['cik', 'as_of', 'kind'], unique=False)
    op.create_table('prices_daily',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('is_adjusted', sa.Boolean(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_document_url', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('data_quality', sa.Enum('current', 'delayed', 'stale', 'unavailable', 'estimated', 'manually_imported', name='data_quality'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('cik', 'trade_date')
    )
    op.create_index(op.f('ix_prices_daily_source_id'), 'prices_daily', ['source_id'], unique=False)
    op.create_index('ix_prices_date', 'prices_daily', ['trade_date'], unique=False)
    op.create_table('scores',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('research_priority', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('convergence', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('contradiction', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('freshness', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('data_quality', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('base', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('category_scores', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('categories_cleared', sa.SmallInteger(), nullable=False),
    sa.Column('categories_total', sa.SmallInteger(), nullable=False),
    sa.Column('weights_version', sa.String(length=32), nullable=False),
    sa.Column('normalization', sa.Enum('percentile', 'fallback_threshold', name='normalization_method'), nullable=False),
    sa.Column('weights_hash', sa.String(length=64), nullable=False),
    sa.CheckConstraint('categories_cleared <= categories_total', name='ck_scores_cleared_bound'),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('cik', 'as_of')
    )
    op.create_index('ix_scores_ranking', 'scores', ['as_of', 'research_priority'], unique=False)
    op.create_table('short_interest',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('settlement_date', sa.Date(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('shares_short', sa.BigInteger(), nullable=False),
    sa.Column('pct_shares_outstanding', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('days_to_cover', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_document_url', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('data_quality', sa.Enum('current', 'delayed', 'stale', 'unavailable', 'estimated', 'manually_imported', name='data_quality'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('cik', 'settlement_date')
    )
    op.create_index(op.f('ix_short_interest_source_id'), 'short_interest', ['source_id'], unique=False)
    op.create_table('short_volume',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('short_volume', sa.BigInteger(), nullable=False),
    sa.Column('total_volume', sa.BigInteger(), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_document_url', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('data_quality', sa.Enum('current', 'delayed', 'stale', 'unavailable', 'estimated', 'manually_imported', name='data_quality'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('cik', 'trade_date')
    )
    op.create_index(op.f('ix_short_volume_source_id'), 'short_volume', ['source_id'], unique=False)
    op.create_table('signal_events',
    sa.Column('event_id', sa.String(length=40), nullable=False),
    sa.Column('category', sa.Enum('corporate_insider', 'political', 'institutional', 'government', 'corporate_event', 'fundamental', 'valuation', 'positioning', 'macro_sector', 'credit', name='signal_category'), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=True),
    sa.Column('disclosure_date', sa.Date(), nullable=True),
    sa.Column('disclosure_lag_days', sa.Integer(), nullable=True),
    sa.Column('public_available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('value_low_minor', sa.BigInteger(), nullable=True),
    sa.Column('value_high_minor', sa.BigInteger(), nullable=True),
    sa.Column('value_exact_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('entity_match_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('underlying_event_key', sa.String(length=128), nullable=True),
    sa.Column('actor_key', sa.String(length=128), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_document_url', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('data_quality', sa.Enum('current', 'delayed', 'stale', 'unavailable', 'estimated', 'manually_imported', name='data_quality'), nullable=False),
    sa.CheckConstraint("(category NOT IN ('political','corporate_insider','institutional')) OR (transaction_date IS NOT NULL AND disclosure_date IS NOT NULL)", name='ck_signal_events_two_dates'),
    sa.CheckConstraint('(value_exact_minor IS NOT NULL)::int + (value_low_minor IS NOT NULL AND value_high_minor IS NOT NULL)::int <= 1', name='ck_signal_events_value_exclusive'),
    sa.CheckConstraint('value_high_minor IS NULL OR value_low_minor IS NULL OR value_high_minor >= value_low_minor', name='ck_signal_events_range_order'),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_signal_events_category_time', 'signal_events', ['category', 'detected_at'], unique=False)
    op.create_index('ix_signal_events_cik_available', 'signal_events', ['cik', 'public_available_at'], unique=False)
    op.create_index(op.f('ix_signal_events_source_id'), 'signal_events', ['source_id'], unique=False)
    op.create_index('ix_signal_events_underlying', 'signal_events', ['underlying_event_key'], unique=False)
    op.create_table('signal_features',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('feature_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('category', sa.Enum('corporate_insider', 'political', 'institutional', 'government', 'corporate_event', 'fundamental', 'valuation', 'positioning', 'macro_sector', 'credit', name='signal_category_feature'), nullable=False),
    sa.CheckConstraint('value IS NOT NULL OR reason_code IS NOT NULL', name='ck_signal_features_missing_has_reason'),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('cik', 'as_of', 'feature_key')
    )
    op.create_table('ticker_map',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.CheckConstraint('valid_to IS NULL OR valid_to >= valid_from', name='ck_ticker_map_order'),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik', 'ticker', 'valid_from', name='uq_ticker_map_period')
    )
    op.create_index('ix_ticker_map_lookup', 'ticker_map', ['ticker', 'valid_from'], unique=False)
    op.create_table('universe_snapshots',
    sa.Column('snapshot_month', sa.Date(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=True),
    sa.Column('in_universe', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'delisted', 'acquired', 'merged', name='company_status'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('snapshot_month', 'cik')
    )
    op.create_table('watchlist_members',
    sa.Column('watchlist_id', sa.BigInteger(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['watchlists.id'], ),
    sa.PrimaryKeyConstraint('watchlist_id', 'cik')
    )
    op.create_table('xbrl_facts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('tag', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_period', sa.String(length=8), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('accession', sa.String(length=25), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_document_url', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('data_quality', sa.Enum('current', 'delayed', 'stale', 'unavailable', 'estimated', 'manually_imported', name='data_quality'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik', 'tag', 'unit', 'period_end', 'filed_date', 'accession', name='uq_xbrl_fact_identity')
    )
    op.create_index('ix_xbrl_asof', 'xbrl_facts', ['cik', 'tag', 'filed_date'], unique=False)
    op.create_index(op.f('ix_xbrl_facts_source_id'), 'xbrl_facts', ['source_id'], unique=False)
    op.create_table('activist_positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filing_accession', sa.String(length=25), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('filer_name', sa.Text(), nullable=False),
    sa.Column('is_activist', sa.Boolean(), nullable=False),
    sa.Column('pct_of_class', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('shares', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('item4_categories', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_document_url', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('data_quality', sa.Enum('current', 'delayed', 'stale', 'unavailable', 'estimated', 'manually_imported', name='data_quality'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.ForeignKeyConstraint(['filing_accession'], ['filings.accession'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_accession', 'filer_name', name='uq_activist_identity')
    )
    op.create_index('ix_activist_cik', 'activist_positions', ['cik', 'effective_date'], unique=False)
    op.create_index(op.f('ix_activist_positions_source_id'), 'activist_positions', ['source_id'], unique=False)
    op.create_table('insider_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('filing_accession', sa.String(length=25), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('insider_cik', sa.String(length=10), nullable=True),
    sa.Column('insider_name', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('is_officer', sa.Boolean(), nullable=False),
    sa.Column('is_director', sa.Boolean(), nullable=False),
    sa.Column('is_ten_percent_owner', sa.Boolean(), nullable=False),
    sa.Column('transaction_code', sa.String(length=1), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('shares', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('price_minor', sa.BigInteger(), nullable=True),
    sa.Column('value_minor', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('shares_owned_after', sa.Numeric(precision=20, scale=4), nullable=True),
    sa.Column('is_10b5_1', sa.Boolean(), nullable=True),
    sa.Column('is_amendment', sa.Boolean(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=True),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('source_document_url', sa.Text(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('data_quality', sa.Enum('current', 'delayed', 'stale', 'unavailable', 'estimated', 'manually_imported', name='data_quality'), nullable=False),
    sa.ForeignKeyConstraint(['cik'], ['companies.cik'], ),
    sa.ForeignKeyConstraint(['filing_accession'], ['filings.accession'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filing_accession', 'insider_name', 'transaction_code', 'transaction_date', 'shares', 'price_minor', name='uq_insider_transaction_identity')
    )
    op.create_index('ix_insider_cik_date', 'insider_transactions', ['cik', 'transaction_date'], unique=False)
    op.create_index('ix_insider_code', 'insider_transactions', ['transaction_code'], unique=False)
    op.create_index(op.f('ix_insider_transactions_source_id'), 'insider_transactions', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_insider_transactions_source_id'), table_name='insider_transactions')
    op.drop_index('ix_insider_code', table_name='insider_transactions')
    op.drop_index('ix_insider_cik_date', table_name='insider_transactions')
    op.drop_table('insider_transactions')
    op.drop_index(op.f('ix_activist_positions_source_id'), table_name='activist_positions')
    op.drop_index('ix_activist_cik', table_name='activist_positions')
    op.drop_table('activist_positions')
    op.drop_index(op.f('ix_xbrl_facts_source_id'), table_name='xbrl_facts')
    op.drop_index('ix_xbrl_asof', table_name='xbrl_facts')
    op.drop_table('xbrl_facts')
    op.drop_table('watchlist_members')
    op.drop_table('universe_snapshots')
    op.drop_index('ix_ticker_map_lookup', table_name='ticker_map')
    op.drop_table('ticker_map')
    op.drop_table('signal_features')
    op.drop_index('ix_signal_events_underlying', table_name='signal_events')
    op.drop_index(op.f('ix_signal_events_source_id'), table_name='signal_events')
    op.drop_index('ix_signal_events_cik_available', table_name='signal_events')
    op.drop_index('ix_signal_events_category_time', table_name='signal_events')
    op.drop_table('signal_events')
    op.drop_index(op.f('ix_short_volume_source_id'), table_name='short_volume')
    op.drop_table('short_volume')
    op.drop_index(op.f('ix_short_interest_source_id'), table_name='short_interest')
    op.drop_table('short_interest')
    op.drop_index('ix_scores_ranking', table_name='scores')
    op.drop_table('scores')
    op.drop_index('ix_prices_date', table_name='prices_daily')
    op.drop_index(op.f('ix_prices_daily_source_id'), table_name='prices_daily')
    op.drop_table('prices_daily')
    op.drop_index('ix_llm_outputs_lookup', table_name='llm_outputs')
    op.drop_table('llm_outputs')
    op.drop_index('ix_ingestion_runs_source_time', table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_government_contracts_source_id'), table_name='government_contracts')
    op.drop_index('ix_contract_cik_date', table_name='government_contracts')
    op.drop_table('government_contracts')
    op.drop_index('ix_filings_cik_form', table_name='filings')
    op.drop_index('ix_filings_available', table_name='filings')
    op.drop_table('filings')
    op.drop_index('ix_entity_matches_below_gate', table_name='entity_matches', postgresql_where=sa.text('confidence < 0.85'))
    op.drop_table('entity_matches')
    op.drop_table('contradiction_items')
    op.drop_index(op.f('ix_congressional_transactions_source_id'), table_name='congressional_transactions')
    op.drop_index('ix_congress_disclosure', table_name='congressional_transactions')
    op.drop_index('ix_congress_cik_date', table_name='congressional_transactions')
    op.drop_table('congressional_transactions')
    op.drop_table('watchlists')
    op.drop_index('ix_raw_documents_source', table_name='raw_documents')
    op.drop_table('raw_documents')
    op.drop_index(op.f('ix_macro_observations_source_id'), table_name='macro_observations')
    op.drop_table('macro_observations')
    op.drop_table('entity_review_queue')
    op.drop_table('data_sources')
    op.drop_index('ix_companies_sector', table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_benchmark_prices_daily_source_id'), table_name='benchmark_prices_daily')
    op.drop_table('benchmark_prices_daily')
    # ### end Alembic commands ###
