"""initial schema

Revision ID: ed2dc77df413
Revises: 
Create Date: 2026-08-18 12:53:33.810870

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ed2dc77df413'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=32), server_default='company', nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('cik', sa.String(length=10), nullable=True),
    sa.Column('lei', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('sector', sa.Text(), nullable=True),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('sic_code', sa.String(length=8), nullable=True),
    sa.Column('fiscal_year_end', sa.String(length=4), nullable=True),
    sa.Column('is_financial', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('data_quality_flag', sa.String(length=32), server_default='ok', nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_quality_flag IN ('ok', 'unverified_bootstrap', 'missing', 'quarantined', 'stale', 'conflicted', 'suspect_unit', 'premium_dependent')", name='ck_entities_dq_flag'),
    sa.CheckConstraint("entity_type IN ('company', 'fund', 'index', 'government')", name='ck_entities_entity_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cik')
    )
    op.create_index('ix_entities_cik', 'entities', ['cik'], unique=False)
    op.create_table('macro_observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('series_id', sa.String(length=64), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('realtime_start', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('value_type', sa.String(length=24), server_default='observed', nullable=False),
    sa.Column('data_quality_flag', sa.String(length=32), server_default='ok', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("value_type IN ('observed', 'calculated', 'estimated', 'ai_interpreted')", name='ck_macro_value_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('series_id', 'obs_date', 'source', name='uq_macro_series_date_source')
    )
    op.create_index('ix_macro_series_date', 'macro_observations', ['series_id', 'obs_date'], unique=False)
    op.create_table('workflow_jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('job_type', sa.String(length=48), nullable=False),
    sa.Column('target_ref', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rows_written', sa.Integer(), nullable=True),
    sa.Column('rows_quarantined', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'succeeded', 'failed')", name='ck_jobs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_type_status', 'workflow_jobs', ['job_type', 'status'], unique=False)
    op.create_table('analyst_estimates',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('estimate_date', sa.Date(), nullable=False),
    sa.Column('mean_estimate', sa.Numeric(precision=28, scale=4), nullable=True),
    sa.Column('analyst_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('value_type', sa.String(length=24), server_default='estimated', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entity_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_entity_id', sa.Integer(), nullable=False),
    sa.Column('child_entity_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('ownership_pct', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('parent_entity_id <> child_entity_id', name='ck_entity_rel_not_self'),
    sa.ForeignKeyConstraint(['child_entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['parent_entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_entity_id', 'child_entity_id', 'relationship_type', 'effective_date', name='uq_entity_rel')
    )
    op.create_table('filings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('accession_number', sa.String(length=32), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('acceptance_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_of_report', sa.Date(), nullable=True),
    sa.Column('primary_doc_url', sa.Text(), nullable=True),
    sa.Column('items', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number')
    )
    op.create_index('ix_filings_entity_filed', 'filings', ['entity_id', 'filed_date'], unique=False)
    op.create_index('ix_filings_form', 'filings', ['form_type'], unique=False)
    op.create_table('fundamentals',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=128), nullable=False),
    sa.Column('xbrl_tag', sa.String(length=128), nullable=True),
    sa.Column('taxonomy', sa.String(length=24), nullable=True),
    sa.Column('metric_value', sa.Numeric(precision=28, scale=4), nullable=True),
    sa.Column('unit', sa.String(length=24), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=True),
    sa.Column('fiscal_period', sa.String(length=8), nullable=True),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('form_type', sa.String(length=16), nullable=True),
    sa.Column('accession_number', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('value_type', sa.String(length=24), server_default='observed', nullable=False),
    sa.Column('data_quality_flag', sa.String(length=32), server_default='ok', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_quality_flag IN ('ok', 'unverified_bootstrap', 'missing', 'quarantined', 'stale', 'conflicted', 'suspect_unit', 'premium_dependent')", name='ck_fundamentals_dq_flag'),
    sa.CheckConstraint("value_type IN ('observed', 'calculated', 'estimated', 'ai_interpreted')", name='ck_fundamentals_value_type'),
    sa.CheckConstraint('period_start IS NULL OR period_start <= period_end', name='ck_fundamentals_period_order'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'metric_name', 'period_end', 'fiscal_period', 'filed_date', 'accession_number', 'source', name='uq_fundamentals_fact')
    )
    op.create_index('ix_fundamentals_period', 'fundamentals', ['entity_id', 'metric_name', 'period_end'], unique=False)
    op.create_index('ix_fundamentals_pit', 'fundamentals', ['entity_id', 'metric_name', 'filed_date'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=24), nullable=False),
    sa.Column('exchange', sa.String(length=24), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('security_type', sa.String(length=32), server_default='common_stock', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('stooq_symbol', sa.String(length=32), nullable=True),
    sa.Column('data_quality_flag', sa.String(length=32), server_default='ok', nullable=False),
    sa.Column('first_seen', sa.Date(), nullable=True),
    sa.Column('last_seen', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_quality_flag IN ('ok', 'unverified_bootstrap', 'missing', 'quarantined', 'stale', 'conflicted', 'suspect_unit', 'premium_dependent')", name='ck_securities_dq_flag'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker', 'exchange', name='uq_securities_ticker_exchange')
    )
    op.create_index('ix_securities_entity_id', 'securities', ['entity_id'], unique=False)
    op.create_index('ix_securities_ticker', 'securities', ['ticker'], unique=False)
    op.create_table('data_conflicts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('table_name', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('metric_name', sa.String(length=128), nullable=True),
    sa.Column('obs_date', sa.Date(), nullable=True),
    sa.Column('conflict_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), server_default='warning', nullable=False),
    sa.Column('source_a', sa.String(length=32), nullable=True),
    sa.Column('value_a', sa.Numeric(precision=28, scale=4), nullable=True),
    sa.Column('source_b', sa.String(length=32), nullable=True),
    sa.Column('value_b', sa.Numeric(precision=28, scale=4), nullable=True),
    sa.Column('pct_difference', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('resolved', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("conflict_type IN ('cross_source_disagreement', 'impossible_value', 'timestamp_sanity', 'unit_mismatch', 'duplicate', 'staleness', 'adjustment_inconsistency')", name='ck_conflicts_type'),
    sa.CheckConstraint("severity IN ('info', 'warning', 'critical')", name='ck_conflicts_severity'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conflicts_security', 'data_conflicts', ['security_id'], unique=False)
    op.create_index('ix_conflicts_unresolved', 'data_conflicts', ['resolved', 'detected_at'], unique=False)
    op.create_table('insider_transactions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('insider_name', sa.Text(), nullable=False),
    sa.Column('insider_cik', sa.String(length=10), nullable=True),
    sa.Column('is_director', sa.Boolean(), nullable=True),
    sa.Column('is_officer', sa.Boolean(), nullable=True),
    sa.Column('is_ten_pct_owner', sa.Boolean(), nullable=True),
    sa.Column('officer_title', sa.Text(), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('filed_date', sa.Date(), nullable=False),
    sa.Column('transaction_code', sa.String(length=4), nullable=True),
    sa.Column('acquired_disposed', sa.String(length=1), nullable=True),
    sa.Column('shares', sa.Numeric(precision=28, scale=4), nullable=True),
    sa.Column('price_per_share', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('shares_owned_after', sa.Numeric(precision=28, scale=4), nullable=True),
    sa.Column('is_derivative', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('accession_number', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('value_type', sa.String(length=24), server_default='observed', nullable=False),
    sa.Column('data_quality_flag', sa.String(length=32), server_default='ok', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("value_type IN ('observed', 'calculated', 'estimated', 'ai_interpreted')", name='ck_insider_value_type'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number', 'insider_cik', 'transaction_date', 'transaction_code', 'shares', 'is_derivative', name='uq_insider_txn')
    )
    op.create_index('ix_insider_entity_filed', 'insider_transactions', ['entity_id', 'filed_date'], unique=False)
    op.create_table('options_chain_observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('strike', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('option_type', sa.String(length=4), nullable=False),
    sa.Column('implied_volatility', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('political_trades',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('politician_name', sa.Text(), nullable=False),
    sa.Column('chamber', sa.String(length=8), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('ticker_raw', sa.String(length=32), nullable=True),
    sa.Column('asset_description', sa.Text(), nullable=True),
    sa.Column('transaction_type', sa.String(length=32), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('disclosure_date', sa.Date(), nullable=False),
    sa.Column('amount_range_low', sa.Numeric(precision=28, scale=4), nullable=True),
    sa.Column('amount_range_high', sa.Numeric(precision=28, scale=4), nullable=True),
    sa.Column('firewall_status', sa.String(length=32), server_default='investigate_only', nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=24), server_default='observed', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("firewall_status IN ('investigate_only', 'excluded')", name='ck_political_firewall_status'),
    sa.CheckConstraint('disclosure_date >= transaction_date', name='ck_political_disclosure_after_txn'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_political_disclosure', 'political_trades', ['disclosure_date'], unique=False)
    op.create_table('price_observations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('obs_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=20, scale=6), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('is_split_adjusted', sa.Boolean(), nullable=True),
    sa.Column('is_dividend_adjusted', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('value_type', sa.String(length=24), server_default='observed', nullable=False),
    sa.Column('data_quality_flag', sa.String(length=32), server_default='ok', nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("data_quality_flag IN ('ok', 'unverified_bootstrap', 'missing', 'quarantined', 'stale', 'conflicted', 'suspect_unit', 'premium_dependent')", name='ck_price_dq_flag'),
    sa.CheckConstraint("value_type IN ('observed', 'calculated', 'estimated', 'ai_interpreted')", name='ck_price_value_type'),
    sa.CheckConstraint('(open IS NULL OR open >= 0) AND (high IS NULL OR high >= 0) AND (low IS NULL OR low >= 0) AND (close IS NULL OR close >= 0) AND (adj_close IS NULL OR adj_close >= 0)', name='ck_price_non_negative'),
    sa.CheckConstraint('volume IS NULL OR volume >= 0', name='ck_price_volume_non_negative'),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'obs_date', 'source', name='uq_price_sec_date_source')
    )
    op.create_index('ix_price_sec_date', 'price_observations', ['security_id', 'obs_date'], unique=False)
    op.create_table('research_snapshots',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=True),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('investment_quality_score', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('trade_setup_score', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=20, scale=10), nullable=True),
    sa.Column('components_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('inputs_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence_score IS NULL OR (confidence_score >= 0 AND confidence_score <= 100)', name='ck_snapshot_conf_range'),
    sa.CheckConstraint('investment_quality_score IS NULL OR (investment_quality_score >= 0 AND investment_quality_score <= 100)', name='ck_snapshot_iq_range'),
    sa.CheckConstraint('trade_setup_score IS NULL OR (trade_setup_score >= 0 AND trade_setup_score <= 100)', name='ck_snapshot_ts_range'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_snapshots_entity_date', 'research_snapshots', ['entity_id', 'as_of_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_snapshots_entity_date', table_name='research_snapshots')
    op.drop_table('research_snapshots')
    op.drop_index('ix_price_sec_date', table_name='price_observations')
    op.drop_table('price_observations')
    op.drop_index('ix_political_disclosure', table_name='political_trades')
    op.drop_table('political_trades')
    op.drop_table('options_chain_observations')
    op.drop_index('ix_insider_entity_filed', table_name='insider_transactions')
    op.drop_table('insider_transactions')
    op.drop_index('ix_conflicts_unresolved', table_name='data_conflicts')
    op.drop_index('ix_conflicts_security', table_name='data_conflicts')
    op.drop_table('data_conflicts')
    op.drop_index('ix_securities_ticker', table_name='securities')
    op.drop_index('ix_securities_entity_id', table_name='securities')
    op.drop_table('securities')
    op.drop_index('ix_fundamentals_pit', table_name='fundamentals')
    op.drop_index('ix_fundamentals_period', table_name='fundamentals')
    op.drop_table('fundamentals')
    op.drop_index('ix_filings_form', table_name='filings')
    op.drop_index('ix_filings_entity_filed', table_name='filings')
    op.drop_table('filings')
    op.drop_table('entity_relationships')
    op.drop_table('analyst_estimates')
    op.drop_index('ix_jobs_type_status', table_name='workflow_jobs')
    op.drop_table('workflow_jobs')
    op.drop_index('ix_macro_series_date', table_name='macro_observations')
    op.drop_table('macro_observations')
    op.drop_index('ix_entities_cik', table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
