/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Root
         * @description Unprefixed alias. Phase 1 criterion 2 curls this exact path.
         */
        get: operations["health_root_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/system/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Sources
         * @description KPI card 6 and the sidebar coverage ring read this.
         *
         *     The source count is computed from config/sources.yaml -- UI_SPEC §2 is
         *     explicit that "15/15" must never be hardcoded.
         */
        get: operations["list_sources_api_v1_system_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Coverage */
        Coverage: {
            /** Categories Available */
            categories_available: number;
            /** Categories Total */
            categories_total: number;
        };
        /** Envelope[list[SourceState]] */
        Envelope_list_SourceState__: {
            /** Data */
            data: components["schemas"]["SourceState"][];
            meta: components["schemas"]["Meta"];
        };
        /** Meta */
        Meta: {
            /** As Of */
            as_of?: string | null;
            /**
             * Generated At
             * Format: date-time
             */
            generated_at: string;
            /** Data Quality */
            data_quality?: number | null;
            /** Sources */
            sources?: components["schemas"]["SourceState"][];
            /** Weights Version */
            weights_version?: string | null;
            /** Normalization */
            normalization?: string | null;
            coverage?: components["schemas"]["Coverage"] | null;
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** SourceState */
        SourceState: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "current" | "delayed" | "stale" | "unavailable" | "failed";
            /** Last Success */
            last_success?: string | null;
            /** Reason */
            reason?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_root_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_sources_api_v1_system_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_SourceState__"];
                };
            };
        };
    };
}
